version: '3.1'
services:
    backend:
        image: gcr.io/bidder-test-216816/node
        container_name: app-backend
        volumes:
            - ./backend:/app
        working_dir: /app
        entrypoint: ash -c 'npm install && npm run build && npm run dev'
        depends_on:
            - mongo
        networks:
            app_nw:
                ipv4_address: 172.11.0.2
    server:
        image: gcr.io/bidder-test-216816/node-server
        container_name: app-server
        volumes:
            - ./server:/app
        working_dir: /app
        entrypoint: ash -c 'npm install && npm run compile && npm run dev'
        depends_on:
            - mongo
        networks:
            app_nw:
                ipv4_address: 172.11.0.5
    mongo:
        container_name: app-mongo-db
        ports:
        - "27017:27017"
        image: mongo
        volumes:
        - ./data:/data/db
        networks:
            app_nw:
                ipv4_address: 172.11.0.3
    angular:
        image: angular-coursera
        ports:
        - "4200:4200"
        - "49153:49153"
        volumes:
        - ./ui:/app
        working_dir: /app
        entrypoint: ash -c 'npm install && npm rebuild node-sass && npm run build && npm run start'
        container_name: app-ui
        networks:
            app_nw:
                ipv4_address: 172.11.0.4

networks:
    app_nw:
        ipam:
            config:
            - subnet: 172.11.0.0/24
