version: '3.1'
services:
    api:
        image: express-generator
        container_name: app-api
        volumes:
            - ./conFusionServer:/app
        working_dir: /app
        entrypoint: ash -c 'npm run start'
        depends_on:
            - mongo
        networks:
            app_nw:
                ipv4_address: 172.11.0.5
        ports:
            - "8090:8090"
#    backend:
#        image: express
#        container_name: app-backend
#        volumes:
#            - ./backend:/app
#        working_dir: /app
#        entrypoint: ash -c 'npm run build && npm run dev'
#        depends_on:
#            - mongo
#        networks:
#            app_nw:
#                ipv4_address: 172.11.0.2
#        ports:
#            - "8090:8090"
    mongo:
        container_name: app-mongo
        ports:
            - "27017:27017"
        image: mongo
        volumes:
          - ./data:/data/db
        networks:
            app_nw:
                ipv4_address: 172.11.0.3
    ui:
        image: angular
        container_name: app-ui
        volumes:
            - ./ui:/usr/app
        working_dir: /usr/app
        entrypoint: ash -c 'npm run start'
        networks:
            app_nw:
                ipv4_address: 172.11.0.4
        ports:
            - "4200:4200"
            - "49153:49153"
        expose:
            - "4200"
            - "49153"

networks:
    app_nw:
        ipam:
            config:
                - subnet: 172.11.0.0/24

