version: '3.1'
services:
    backend:
        image: gcr.io/bidder-test-216816/node
        container_name: app-server
        volumes:
            - ./backend:/app
        working_dir: /app
        entrypoint: ash -c 'npm install && npm run dev'
        depends_on:
            - mongo
        networks:
            app_nw:
                ipv4_address: 172.11.0.2
        ports:
            - "8090:8090"
    mongo:
        container_name: app-mongo-db
        ports:
            - "27017:27017"
        image: mongo
        volumes:
          - ./data:/data/db
        networks:
            app_nw:
                ipv4_address: 172.11.0.3
    angular:
        image: gcr.io/bidder-test-216816/angular
        volumes:
            - ./ui:/usr/app
        working_dir: /usr/app
        entrypoint: ash -c 'npm run start'
        container_name: app-ui
        networks:
            app_nw:
                ipv4_address: 172.11.0.4
        ports:
            - "4200:4200"
            - "49153:49153"
        expose:
            - "4200"
            - "49153"

networks:
    app_nw:
        ipam:
            config:
                - subnet: 172.11.0.0/24

